### ISSUE TITLE
Google docstring standard not rendering correctly.

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2PythonAPI#102]
@ocefpaf I tested out the docstring on my latest change #98. But `Args` doesn't seem to be rendering correctly.. Should I add `*` or `-` to make it a list?

<img width="665" alt="screenshot 2017-09-29 08 26 48" src="https://user-images.githubusercontent.com/17802172/31023374-78abc15a-a4f0-11e7-94e7-98563db2ebf5.png">

**Comment by ocefpaf** [comment]
Let me check it locally.. Hold on. (sphinx is very annoying with the indentation.)

**Comment by lsetiawan** [comment]
I did this on the `.rst`

```
:mod:`Read Services`
----------------------

.. automodule:: odm2api.ODM2.services.readService
   :members:
   :undoc-members:
   :show-inheritance:
```
