### ISSUE TITLE
Avoid the use of builtins

### ISSUE THREAD

**Issue by ocefpaf** [ODM2/ODM2PythonAPI#115]
`ODM2PythonAPI` uses obfuscate Python builtins in some places.

The links belong point to two blocks of code that use the reserved word `type`.

[odm2api/ODM2/services/readService.py#L81-L121](https://github.com/ODM2/ODM2PythonAPI/blob/master/odm2api/ODM2/services/readService.py#L81-L121)
[odm2api/ODM2/services/readService.py#L365-L390](https://github.com/ODM2/ODM2PythonAPI/blob/master/odm2api/ODM2/services/readService.py#L365-L390)

It would be nice if we can renamed those to something else. I already addressed most on them in #111.
However, I did not address those that are used as `args` to avoid braking the current `API`.

**Comment by emiliom** [comment]
PR #117 has addressed most/all of the uses of the Python `builtin` (reserved word) `type`, with a nice, unobtrusive deprecation path.

Are there other misused `builtins` we know of, or can this issue be closed once PR #117 is merged? Or should we leave this issue open as a reminder to look for additional cases that will need to be fixed?

**Comment by emiliom** [comment]
Following up on PR #138

> Missed the builtins type in getCVs function. This should be the last ones, according to travis-CI.

Do you mean the last type builtin, or the last builtin altogether (ie, no more misuse of builtins!)? If it's the latter, we can close this issue. Woo-hoo!

**Comment by lsetiawan** [comment]
Based on the report of TravisCI, I do not see anymore error for builtin abuse in the code. :smile:

**Comment by emiliom** [comment]
Woo-hoo indeed! Closing the issue.
