### ISSUE TITLE
Need new read function samplingfeaturesdatasets

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2PythonAPI#120]
### Description
Retrieve a list of sampling features along with metadata about their associated datasets.
### Returns
List of sampling feature objects along with their associated datasets
### Available Query Parameters (must specify either samplingFeatureID OR samplingFeatureUUID OR samplingFeatureCode)

- samplingFeatureID: return sampling features for a list of samplingFeatureIDs
- samplingFeatureUUID: return sampling features for a list of samplingFeatureUUIDs
- samplingFeatureCode:  return information for a specific sampling feature or list of sampling features
- datasetType: return datasets for a list of particular datasetTypes

This relates to the development of ODM2RESTAPI issue https://github.com/ODM2/ODM2RESTfulWebServices/issues/19

**Comment by horsburgh** [comment]
@sreeder is back today, so I'm assigning this to her.

**Comment by lsetiawan** [comment]
Sounds good! Thanks @horsburgh. @sreeder Please let me know when you have this ready so I can implement it. 😃

**Comment by lsetiawan** [comment]
Already created. See #121. Closing.
