### ISSUE TITLE
Add related-sampling-features object methods

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2PythonAPI#124]
ie., give a sampling feature object a method like "get related sampling features."

**Comment by emiliom** [comment]
Has this been implemented already? If not, @lsetiawan, does it seem like something we (ok, you!) could implement fairly easily? @horsburgh, any thoughts?

**Comment by lsetiawan** [comment]
Not sure, I'll have to look at the code in detail first.

**Comment by horsburgh** [comment]
@emiliom - I don't believe this specific function has been implemented yet. I think @Elijahwalkerwest and @Maurier may have iterated on another endpoint that may have something similar in it. @Elijahwalkerwest - did you do something similar in the getSamplingFeatureDatasets function?

**Comment by Elijahwalkerwest** [comment]
Similar feature yes but the implementation is different. How do we want this inplemented exactly? Do we want the samoling feature end point to just return related features as well?

**Comment by horsburgh** [comment]
@Elijahwalkerwest - just wondering if there was code we already developed that we could reuse. Good question about the getSamplingFeatures function. @emiliom - do you have a a preference for a separate function?  It might be easier to implement and wouldn't break anything that currently uses getSamplingFeatures.

**Comment by Elijahwalkerwest** [comment]
No, cant reuse the code exactly but near enough that it wouldnt be hard to implement.  As far as im aware theres already a pythonapi get related features. So either restful endpoiny or roll it in to getsamplingfeatures. Shouldnt be hard either way.

**Comment by horsburgh** [comment]
Ah - well, @Elijahwalkerwest, this issue is in the ODM2 PythonAPI repo, so if there is already a getRelatedSamplingFeatures can you provide a link to the code here and then we can close this issue right?

**Comment by Elijahwalkerwest** [comment]
Oof. Commenting on mobile and forgot to look. Yeah im using it in the getsamplingfeaturedatasets actually. Let me double check when i get in to work tomorrow and link the relevant code and close.

**Comment by emiliom** [comment]
> @emiliom - do you have a a preference for a separate function? It might be easier to implement and wouldn't break anything that currently uses getSamplingFeatures.

I would agree.

**Comment by lsetiawan** [comment]
Here's [`getRelatedSamplingFeatures`](https://github.com/ODM2/ODM2PythonAPI/blob/master/odm2api/ODM2/services/readService.py#L436) in the readServices. Thanks @Elijahwalkerwest and @horsburgh, I should've known this existed. :disappointed: *sigh* Still have traces of holiday brain i guess haha.

**Comment by emiliom** [comment]
Thanks for finding this, @lsetiawan. 
Closing the issue

**Comment by emiliom** [comment]
It looks like `getRelatedSamplingFeatures` had actually been around since April 2016. See [599b6cd](https://github.com/ODM2/ODM2PythonAPI/commit/599b6cd8885f7a2956f1b9d1f394e983b9fa5935).
