### ISSUE TITLE
geoalchemy vs geoalchemy2 dependency

### ISSUE THREAD

**Issue by emiliom** [ODM2/ODM2PythonAPI#13]
@sreeder and @horsburgh: I'm creating this issue to help us keep track of the status.

Stephanie, were you able to make progress on this last week?

**Comment by sreeder** [comment]
This issue has been completed in the geometry branch and has been merged into the setup branch

**Comment by emiliom** [comment]
@sreeder, one question: when we talked on the phone I *think* you said that using geoalchemy would involve making some changes to it. Was that the case, or am I mixing things up? If it is true, it means we'll have to maintain our own fork of geoalchemy in the ODM2 github organization. Not a problem per se, just wanted to make that clear.

**Comment by sreeder** [comment]
@emiliom Yes, there is one classname that has to be changed. I have made a note of it in the requirements.txt file. But I have been planning on keeping our own copy in the repository, thanks for the reminder.

**Comment by emiliom** [comment]
This is just for reference:
- Stephanie's change to geoalchemy (copied from [requirements.txt](https://github.com/ODM2/ODM2PythonAPI/blob/setup_em/requirements.txt)): Change [line #242 in geoalchemy/base.py](https://github.com/geoalchemy/geoalchemy/blob/master/geoalchemy/base.py#L242) from: `class SpatialComparator(ColumnProperty.ColumnComparator):` to `class SpatialComparator(ColumnProperty.Comparator):`
- A [2014-Aug report on the same `import geoalchemy` error](https://groups.google.com/forum/#!topic/geoalchemy/CANgc_cbyVI), from the geoalchemy Google Groups list. No one replied (that's not surprising).

**Comment by emiliom** [comment]
I've forked geoalchemy into the ODM2 org: https://github.com/ODM2/geoalchemy. Then I created a branch (`odm2`) and made Stephanie's single-line edit there. Then I tested by first installing this fork/branch via `pip install git+https://github.com/ODM2/geoalchemy.git@odm2`, then installing odm2api (setup_em branch) via `pip install git+https://github.com/ODM2/ODM2PythonAPI.git@setup_em`. 

So far so good! `import odm2api` and `import geoalchemy` didn't complain.

I don't know how to specify a github repo, rather than the pypi default, as the source of a dependency requirement; so I didn't change the requirements/setup files in odm2api. Hopefully @sreeder can take care of that, specially once we promote my geoalchemy odm2 branch to master (I was just being extra careful).

**Comment by emiliom** [comment]
Things to follow up on, probably as separate issues:
- Is [odm2api.ODM2.apiCustomType](https://github.com/ODM2/ODM2PythonAPI/blob/setup_em/odm2api/ODM2/apiCustomType.py) no longer used anywhere? I assume so, b/c it has a `geoalchemy2` import statement, so that would throw an error. If this is the case, it should be removed (or better yet, an experimental geoalchemy2 branch should be created and used as a future reference/archive). But I wonder if the now missing functionality from that module is related to the [possible problems/unexpected behavior I've run into](https://github.com/ODM2/ODM2PythonAPI/issues/11#issuecomment-162392196).
- In [odm2api.ODM2.models](https://github.com/ODM2/ODM2PythonAPI/blob/setup_em/odm2api/ODM2/models.py#L11), the use of `from geoalchemy import *` should be changed so `geoalchemy` is imported with a namespace. Importing everything makes debugging more difficult, and may lead to unexpected conflicts.
- [SamplingFeatures.FeatureGeometry is currently hardwired](https://github.com/ODM2/ODM2PythonAPI/blob/setup_em/odm2api/ODM2/models.py#L561) (in odm2api.ODM2.models) to support only Point feature types. This will need to be addressed, but that can happen in follow-up development, say in a geometry branch.

**Comment by sreeder** [comment]
@emiliom 
you are correct, the apiCustomType is no longer being used.
I will work on changing over the import statement and see if there is a simple way to expand the support of feature types beyond Point. I'm not sure the best way to address the shaply issue at the moment but I may be able to write a custom __repr__ function that will print it out as WKT.

**Comment by valentinedwv** [comment]
I changed the dependencies in setup.py and requirements.txt.
On Windows you may/will need to add git to your path. for me it was:
C:\Program Files (x86)\Git\cmd

**Comment by emiliom** [comment]
Thanks, @valentinedwv ! Have you tested this? I tried installing, letting `pip install git+https://github.com/ODM2/ODM2PythonAPI.git` handle the geoalchemy dependency. Instead of installing odm2/geoalchemy.git@odm2 (labelled as version 0.7.3dev), it installed geoalchemy from pypi (0.7.2).

I don't know enough about pip packaging to figure out what's wrong.

**Comment by emiliom** [comment]
Just more confirmation that the setup dependency requirement for geoalchemy is not configured correctly. My odm2api tests ran just fine when I pre-installed geoalchemy via pip install, like this:
```
pip install git+https://github.com/ODM2/geoalchemy.git@odm2
pip install git+https://github.com/ODM2/ODM2PythonAPI.git
```

**Comment by valentinedwv** [comment]
Didn't hard core check it, but when I ran it in pycharm, it complained about not pulling from git...
Checking now pycharm shows 0.7.3.dev0

Added >= to geoalchemy to see if that forces it.

**Comment by emiliom** [comment]
Do you use conda? I can send you instructions for installing odm2api with
all dependencies, with conda. It's very easy.

**Comment by emiliom** [comment]
Has anyone tested Dave's latest change to the geoalchemy dependency specification? ie, is the right geoalchemy version installed when pip installing odm2api?

**Comment by horsburgh** [comment]
@emiliom - Not sure I'm on track here, but to test the API (which I have been doing a little over the past couple of days), I used these instructions from Stephanie to get a Python environment named "sdl" set up using conda:

conda create -n sdl sqlalchemy pymysql psycopg2 pyodbc shapely pandas pyyaml ipython-notebook
source activate sdl
pip install git+https://github.com/ODM2/Geoalchemy.git@master
pip install git+https://github.com/ODM2/ODM2PythonAPI.git@master

Then, I had to manually change line 242 in the file: 

/anaconda/envs/sdl/lib/python2.7/site-packages/geoalchemy/base.py 

From:    class SpatialComparator(ColumnProperty.ColumnComparator):
To:         class SpatialComparator(ColumnProperty.Comparator):

It seems like if we are maintaining our own copy of Geoalchemy and I'm using pip to install, I shouldn't have to do this last step???

**Comment by emiliom** [comment]
> It seems like if we are maintaining our own copy of Geoalchemy and I'm using pip to install, I shouldn't have to do this last step???

You're right. And that [hasn't been needed for over two weeks](https://github.com/ODM2/ODM2PythonAPI/issues/13#issuecomment-162382330). The right installation statements are:
```
pip install git+https://github.com/ODM2/geoalchemy.git@odm2
pip install git+https://github.com/ODM2/ODM2PythonAPI.git
```
- No need to specify `@master` on odm2api itself
- Currently the change on our geoalchemy fork is on the `odm2` branch. We could easily merge it to master; I just wanted to let others (@sreeder? you?) have a chance to comment first.

What @valentinedwv was/is working on was correctly building in the geoalchemy dependency specification for odm2api, so that pip installing odm2api will take care of geoalchemy directly, w/o the user needing to explicitly install geoalchemy.

**Comment by emiliom** [comment]
Closing this issue. I've created instructions for installing `odm2api` using conda packages for all the dependencies except geoalchemy, followed by a single `pip install` command to install odm2api and geoalchemy. See [README.md](https://github.com/ODM2/ODM2PythonAPI).

Gory packaging details can be found on issue #18 and associated pull requests (PR #19 and PR #20).
