### ISSUE TITLE
Issue new release?

### ISSUE THREAD

**Issue by emiliom** [ODM2/ODM2PythonAPI#135]
Some important enhancements and bug fixes were issued last month, at least on a development branch. These are needed by the ODM2 REST API (https://github.com/ODM2/ODM2RESTfulWebServices/issues/59)

Besides, the [last odm2api tagged release](https://github.com/ODM2/ODM2PythonAPI/releases/tag/v0.6.0-alpha) was issued 6 months ago. So, it seems like this is a good time to work towards a new release.

@horsburgh, do you agree? Someone from your team would need to take the initiative to merge the relevant dev branch into master. Then, if you'd like our help, Don and I can issue the tagged release.

In the meantime, I've added comments to 3 of the latest issues (#118, #124, #127) to learn about the status of the bugs or enhancements they discussed, and see if any of them can go into the next release.

Thanks!

cc @aufdenkampe

**Comment by emiliom** [comment]
- #124 was [already implemented](https://github.com/ODM2/ODM2PythonAPI/blob/master/odm2api/ODM2/services/readService.py#L436) (see it on the [API docs](http://odm2.github.io/ODM2PythonAPI/modules.html#odm2api.ODM2.services.readService.ReadODM2.getRelatedSamplingFeatures). 
  - @lsetiawan, can you confirm that it was added in the last 6 months? In that case, we'll add this to the release notes.
- #127 was addressed on 1/6. **This will be a disruptive change** (all existing code that uses output from this function will need to be upgraded to the case-sensitive dataframe column names), so we'll need to advertise the change in advance.

Let's start compiling here all major new features and major bug fixes, to go into the release notes.

**Comment by lsetiawan** [comment]
> #124 was already implemented (see it on the API docs.) can you confirm that it was added in the last 6 months? In that case, we'll add this to the release notes.

It looks like `getRelatedSamplingFeatures` has been around since April 2016 See https://github.com/ODM2/ODM2PythonAPI/commit/599b6cd8885f7a2956f1b9d1f394e983b9fa5935.

**Comment by lsetiawan** [comment]
The last release was in May 26, 2017. Here are the major changes that occurred to the API since then.
- #96 Fix person and organization filter for affiliations.
- #98 Improve documentation to follow google doc style. (Still Ongoing)
- #99 Created a sphinx based Documentation
- #111 Python 3 Compatibility and Flake 8 Improvements
- #121 Created `getSamplingFeatureDatasets`
- #122 Created `getDatasetsResults` and Improved `getDatasets`
- #123 Improved `getResults`
- #125 Updated the structure of the resulting object from `getSamplingFeatureDatasets`
- #129 Fix bug in `getProcessingLevels`
- #131 Fix bug in `getSamplingFeatureDatasets`
- #134 Fix bug in model `DataloggerFiles` and `DataloggerFileColumns`

**Comment by aufdenkampe** [comment]
On today's BiG CZ call, we decided:

1. Tag release as "Release 0.7.0", removing “pre-release”, “alpha” and/or “beta” tags. We're well beyond that, with 6 previous releases and several repos that now depend on this one!

2. Start using Milestones to organize issues for the next release. We've used them well in other repos, but haven't done a good job with this repo. See https://github.com/ODM2/ODM2PythonAPI/milestones.

**Comment by aufdenkampe** [comment]
@lsetiawan, do you think you could look at the remaining open issues in these open Milestones and close both issues and Milestones if you think they were completed?

- [ ] Milestone: alpha Release 0.5. https://github.com/ODM2/ODM2PythonAPI/milestone/1
- [ ] Milestone: 0.6.0. https://github.com/ODM2/ODM2PythonAPI/milestone/2

You could even create a new Milestone 0.7, then tag all the fixed issues (closed or still open) as you list above with that Milestone, to keep track of which issues were completed with this release.

**Comment by emiliom** [comment]
New release is now ready and stamped:
https://github.com/ODM2/ODM2PythonAPI/releases/tag/v0.7.0
Request for new conda package is in the books, for Filipe:
https://github.com/ODM2/conda-recipes-ODM2/issues/71

Onward and upwards!

There's one issue that I think needs to be discussed soon, before odm2api can be seen as really stable. Currently the package has a packager/folder hierarchy that includes a now-useless "ODM2" folder:
https://github.com/ODM2/ODM2PythonAPI/tree/master/odm2api/ODM2

That forces most module import statements to include the useless ODM2 package hierarchy (eg, `odm2api.ODM2.services.readService`). We'll need to get rid of the ODM2 folder hierarchy, and the sooner we do it the better, to minimize disruptions. I strongly recommend that we do it in the next release, giving ourselves plenty of time for all code that uses odm2api to make the adjustment. 

I can discuss this when I'm back from travels, after the 29th.

**Comment by aufdenkampe** [comment]
@emiliom, thank you for making this release happen, developing helpful release notes, and queuing up a conda package release.

I'm very much a fan of moving forward soon with the next release to remove the useless "ODM2" level of hierarchy, and also changing the default column labels to CamelCase. With release v0.7 minted as is, any software that depends on the old conventions still have handy access to that version, while we can move forward with migrating our actively developed stuff to our widespread conventions.

**Comment by emiliom** [comment]
I'm reopening this only b/c there are some discussions and notes here that I'd like to capture and move elsewhere. FYI, also intend to go back to very old issues to clean up the repo's issues. But that won't happen until mid February.

**Comment by lsetiawan** [comment]
I think we should issue a release of `v0.7.1` before further optimization work. Here are the changes that happened since the last release:
- #143 Added eager loading for `samplingfeaturedataset` to try and cut down on query time.
- #147 Created Future deprecation warning for `ODM2` modules.
- #148 Move to `conda-forge` and deprecate `ODM2` conda channel.
- #151 Updated `README` to reflect changes to `conda-forge` channel and how to install the latest development version.

**Comment by aufdenkampe** [comment]
I think that's a great idea.

**Comment by lsetiawan** [comment]
Following the gitflow workflow, I've created [release/0.7.1](https://github.com/ODM2/ODM2PythonAPI/tree/release/0.7.1) branch. This branch is used for preparing the release. **ONLY bug fixes, documentation generation, and other release-oriented tasks should go in this branch.** So update to the docs mentioned in https://github.com/ODM2/ODM2PythonAPI/issues/146#issuecomment-369310382, should be done in this branch. Thanks. This way further feature development off of the current `development` branch can still happen and not halted while waiting for the release.

**Comment by emiliom** [comment]
Thanks, @lsetiawan! 

Don and I have discussed this new release. The plan is to create it on Friday, or Monday at the latest.

**Comment by emiliom** [comment]
The new release 0.7.1 is out: https://github.com/ODM2/ODM2PythonAPI/releases/tag/v0.7.1

A new conda package will be issued in `conda-forge` early next week.

Thanks @lsetiawan and @Elijahwalkerwest !
