### ISSUE TITLE
createTimeSeriesResultValues

### ISSUE THREAD

**Issue by sreeder** [ODM2/ODM2PythonAPI#15]
The following code should be generic, but there seems to be some issues with capitalization that need to be addressed for all db types
def createTimeSeriesResultValues(self, datavalues):
        try:
            datavalues.to_sql(name="TimeSeriesResultValues",
                              schema=TimeSeriesResultValues.**table_args**['schema'],
                              if_exists='append',
                              chunksize= 1000,
                              con=self._session_factory.engine,
                              index=False)
            self._session.commit()

**Comment by emiliom** [comment]
This is way too old and most likely already long addressed. Closing.
