### ISSUE TITLE
Unecessary Branches Cleanup

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2PythonAPI#152]
I  just notice that there are a lot of old and unnecessary branches that can potentially be cleaned up. I've already cleaned up the most obvious one that doesn't have commits ahead. Here are the list of branches that have some commits ahead, might need some evaluation before deleting:
- https://github.com/ODM2/ODM2PythonAPI/tree/actions
- https://github.com/ODM2/ODM2PythonAPI/tree/pre_alpha_0
- https://github.com/ODM2/ODM2PythonAPI/tree/removeODM1
- https://github.com/ODM2/ODM2PythonAPI/tree/setup_2

Also, I'm not sure if anyone is using https://github.com/ODM2/ODM2PythonAPI/tree/master_10102017 branch. If not then it should probably be deleted since it's way behind. Thanks.

**Comment by horsburgh** [comment]
@Elijahwalkerwest - can you indicate if you need any of these branches? Otherwise, I think they can go @lsetiawan

**Comment by Elijahwalkerwest** [comment]
@horsburgh  @lsetiawan  As far as I can discern there is no need for any of the branches specified.  It's possible Stephanie had some use for them, but none that seems applicable now.

**Comment by lsetiawan** [comment]
@Elijahwalkerwest Great! I will delete them all then.

**Comment by lsetiawan** [comment]
The listed branches has been cleaned up. Closing.
