### ISSUE TITLE
help specifying a build requirement from a github repo release (for geoalchemy fork)

### ISSUE THREAD

**Issue by emiliom** [ODM2/ODM2PythonAPI#18]
@ocefpaf, if you have a bit of time (right!) I'd like to bug -- or beg? :smiley_cat: -- you for help with specifying a package dependency. This isn't conda packaging, yet; that'll be a separate conversation in the future. And it's not IOOS related, at least not yet.

The [ODM2PythonAPI (odm2api) package](https://github.com/ODM2/ODM2PythonAPI) has a dependency on a [slightly customized fork](https://github.com/ODM2/geoalchemy) of the old and no-longer-maintained [geoalchemy "1"](https://github.com/geoalchemy/geoalchemy); FYI, that's the original geoalchemy, *not* the actively maintained `geoalchemy2`. The reasons for having that dependency and tweaking the old code are beyond the scope of this issue, but trust me that they [are valid!](https://github.com/ODM2/ODM2PythonAPI/issues/13#issuecomment-162382330) I can fill you in offline if you really care.

We'd like to be able to update [`setup.py`](https://github.com/ODM2/ODM2PythonAPI/blob/master/setup.py#L82) and/or [`requirements.txt`](https://github.com/ODM2/ODM2PythonAPI/blob/master/requirements.txt#L3) so that our geoalchemy fork will be installed automatically when `od2api` is pip-installed via `pip install git+https://github.com/ODM2/ODM2PythonAPI.git`. Currently I can complete the installation with conda by setting up a conda env with all other dependencies already available via the anaconda main channel or the ioos channel (eg: `conda create -n odm2api python=2.7 sqlalchemy psycopg2 pymysql pyodbc`). Then, on that env, I `pip install git+https://github.com/ODM2/geoalchemy.git`, and *then* `pip install git+https://github.com/ODM2/ODM2PythonAPI.git`. We'd like to be able to specify the setup/requirements so the last step carries out the right geoalchemy installation automatically. What we've tried hasn't worked.

We're not interested in pushing our geoalchemy fork to pypi or anything more formal, for now.

I've just created [a new release for our geoalchemy fork (v0.7.3)](https://github.com/ODM2/geoalchemy/releases/tag/v0.7.3), off the master branch. We don't anticipate any additional changes in the foreseeable future.

I know you're very busy, so if this looks too complicated, no worries if you have to pass. But if it's easy and you can help us, that'd be fantastic! [We](http://odm2.org) are a bit out of our depth here.

**Comment by ocefpaf** [comment]
It seems possible.  I need to take a better look at it during the weekend and I will get back to you.

**Comment by emiliom** [comment]
Done! odm2api is now installable as:
```
pip install --process-dependency-links git+https://github.com/ODM2/ODM2PythonAPI.git
```
This will install the `geoalchemy` dependency from [our odm2 fork ("v0.7.3")](https://github.com/ODM2/geoalchemy/releases/tag/v0.7.3). 

Note that `psycopg2` has been removed from the dependencies, b/c apparently it doesn't install (on Macs and/or Linux?) via `pip install`. Someone should look into this eventually ...

See PR #20 for more details, specially [my last comments](https://github.com/ODM2/ODM2PythonAPI/pull/20#issuecomment-170691770); and PR #19 for preceding tests and discussions.

Thanks to @ocefpaf for helping us with this!!

**Comment by ocefpaf** [comment]
> Thanks to @ocefpaf for helping us with this!!

My pleasure!  (I was enjoy learning something new and I had no idea how `dependency-links` worked before this ;-)
