### ISSUE TITLE
Read service fails for simulation and model functions

### ISSUE THREAD

**Issue by Castronova** [ODM2/ODM2PythonAPI#28]
The `readService` functions fail for most Simulation, Model, and RelatedModel functions.
- `getAllModels`
- `getModelByCode`
- `getAllSimulations`
- `getSimulationByName`
- `getSimulationByActionID`
- `getRelatedModelsByID`
- `getRelatedModelsByCode`
- `getResultsBySimulationID`

**Comment by lsetiawan** [comment]
Update: Seems like all of functions listed above are passing. I think I can close this issue.
