### ISSUE TITLE
Modify API functions to accept arrays of inputs

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2PythonAPI#34]
For some of the API methods it makes sense to pass in an array rather than a single item. For example, getSamplingFeatures( ) will accept a SamplingFeatureID as an argument, but it should accept an array of SamplingFeatureIDs.  Need to list which functions and arguments for which this makes sense.

**Comment by emiliom** [comment]
@sreeder, this has been fully implemented, right? Let's close it.

**Comment by sreeder** [comment]
@emiliom, I actually haven't implemented it yet. It is what I am working on now though.

**Comment by emiliom** [comment]
Ok. For some reason I thought this was one of the many new capabilities now in your Dev1_0 branch.

**Comment by sreeder** [comment]
@emiliom there has been a pull request created to address this issue. So if it is approved we can close this issue. Thanks

**Comment by emiliom** [comment]
> codes and ids are now expected to be a list, even if it only has a single element

@sreeder, I haven't looked at your PR yet (hopefully late today). But I would say that it'd be more user friendly if *either* a scalar or a list can be passed as the argument. I think this is what @horsburgh [was saying when he opened this issue](https://github.com/ODM2/ODM2PythonAPI/issues/34#issue-141932657). It should be fairly easy to implement this via a type check and turning scalar arguments into one-element lists. eg:
```python
if type(arg) != list:
    arg_lst = [arg]
else:
    arg_lst = arg
```

**Comment by horsburgh** [comment]
@emiliom - we discussed this yesterday and we arrived at just using a list.  A list can have one item right?

**Comment by emiliom** [comment]
> A list can have one item right?

Of course. But allowing for a scalar argument is a bit more user-friendly, that's all.

**Comment by horsburgh** [comment]
I know - but there's an argument for consistency too.

@sreeder - what's your call on how difficult it would be to do both?  Should we do this now or should we make this a feature request for another version?

**Comment by emiliom** [comment]
> I know - but there's an argument for consistency too.

Potato potatoh :)

No worries, I won't belabor this. It was just an opinion, and not a strong one. It sounds like you two really prefer to stick with list arguments, so just go with that.
