### ISSUE TITLE
add init function to models

### ISSUE THREAD

**Issue by sreeder** [ODM2/ODM2PythonAPI#36]
add init functions to model classes
current creation happens like this 
![screen shot 2016-03-23 at 10 18 55 am](https://cloud.githubusercontent.com/assets/4721940/14026172/4c1175c4-f1b7-11e5-9557-eb811edb97c5.png)

I think this would be easier
![screen shot 2016-03-23 at 10 20 10 am](https://cloud.githubusercontent.com/assets/4721940/14026188/533d4648-f1b7-11e5-8b01-b9cdba0db324.png)

or this                
![screen shot 2016-03-23 at 10 21 30 am](https://cloud.githubusercontent.com/assets/4721940/14026195/57c904e0-f1b7-11e5-9cc3-ead0b4e47a23.png)

**Comment by sreeder** [comment]
I have created a branch called addinit() to address this issue

**Comment by horsburgh** [comment]
Wouldn't the third option (with named parameters) be more consistent with what we have discussed up to this point for other functions?

**Comment by sreeder** [comment]
I have currently set up the code so the user has to type the full attribute name.  and it is waiting to be merged in a pull request issue #39
