### ISSUE TITLE
Align pypi and anaconda channel packaging and setup efforts

### ISSUE THREAD

**Issue by emiliom** [ODM2/ODM2PythonAPI#49]
@ocefpaf and I are working on a new ODM2 anaconda channel for easy, multi-OS distribution of ODM2 packages (odm2api initially, others later on). We have the [ODM2 channel](https://anaconda.org/odm2) already created with odm2api and its dependencies, already installable on Linux and OSX (some Windows glitches are being worked on).

@valentinedwv is working on PyPI packaging, and [already has this on the test pypi environment](https://testpypi.python.org/pypi/odm2api). He also has overhauled `requirements.txt` and `setup.py` in the [setup_clean branch](https://github.com/ODM2/ODM2PythonAPI/tree/setup_clean) and has a PR ([#46](https://github.com/ODM2/ODM2PythonAPI/pull/46)) waiting in the wings with these changes (I asked to delay merging it for now).

@valentinedwv also has refactored the code to make individual RDBMS packages (eg, `psycopg2`, `pyodbc`) optional user-driven installs, so a MSSQL user never has to care about or install PostgreSQL requirements. See issue #44.

In addition, there's a raft of great new odm2api overhauls that @sreeder has done and I just reviewed, also waiting in the wings. And we're [now using tagged (pre) releases](https://github.com/ODM2/ODM2PythonAPI/releases) (thanks, @sreeder!).

These are all **fantastic** developments!! But it's time to coordinate so we don't trip over each other, we leverage each other's efforts and expertise, and we make the best joint decisions. 

I'll stop here and add a follow-up, next-step comment in a few minutes. I'll ping @aufdenkampe and @horsburgh directly, b/c I think this is important enough that they should be directly aware or involved at least initially.

**Comment by emiliom** [comment]
The packaging and setup experts here are probably @ocefpaf and @valentinedwv (definitely not me!). So I think the first step is probably to have @ocefpaf review the setup changes from @valentinedwv in his PR; [see my brief comment on it](https://github.com/ODM2/ODM2PythonAPI/pull/46#issuecomment-207152718). If we can get agreement between the two of you on `requirements.txt`, `requirements_tests.txt` and `setup.py` to meet the needs of pypi, conda, and github/git-driven development, that'll be fantastic!

**Comment by ocefpaf** [comment]
Sure. I will get to it later today early tomorrow.

**Comment by emiliom** [comment]
Great!

**Comment by valentinedwv** [comment]
For YodaTools, can you add this package to conda: 
valideer

**Comment by emiliom** [comment]
@ocefpaf and @valentinedwv, you've put a lot of effort into stuff related to this. Would you say that we're in good shape now with respect to setup, requirements, packaging and pypi vs conda? If so, we can close this issue.

**Comment by ocefpaf** [comment]
> @ocefpaf and @valentinedwv, you've put a lot of effort into stuff related to this. Would you say that we're in good shape now with respect to setup, requirements, packaging and pypi vs conda? If so, we can close this issue.

:+1:

There is always room for improvement, but it is much better now! Thanks @valentinedwv!!

**Comment by emiliom** [comment]
Great, thanks. Closing now.
