### ISSUE TITLE
Dev1_0 branch ready for merging into master?

### ISSUE THREAD

**Issue by emiliom** [ODM2/ODM2PythonAPI#50]
@sreeder, is the `Dev1_0` ready for merging into master? Or are you planning to do more testing? Would be great to have it merged by the end of the week. We can then issue a new `odm2api` release and update the [conda package](https://anaconda.org/odm2/odm2api). Thanks!

**Comment by emiliom** [comment]
With PR https://github.com/ODM2/ODM2PythonAPI/pull/51 now merged into `Dev1_0` (thanks!!), is `Dev1_0` ready for merging into master?

Before or after that merge we could also move forward with #38 by removing the `ODM1_1_1` stuff, now that @sreeder has preserved it in the [odm1dev](https://github.com/ODM2/ODM2PythonAPI/tree/odm1dev) branch.

**Comment by sreeder** [comment]
@emiliom  I am working on merging Dev1_0 now, but it will break all of the testing stuff so I am pulling the code from master into my branch, fixing the tests, then merging it back into master.

**Comment by emiliom** [comment]
Got it, thanks.

**Comment by sreeder** [comment]
@emiliom  I have started removing `ODM1` in the [removeODM1] (https://github.com/ODM2/ODM2PythonAPI/tree/removeODM1) Branch. I still have some things to fix but should be able to get that done by Monday as well.

**Comment by emiliom** [comment]
@sreeder, that's great! I'm really looking forward to this.

**Comment by emiliom** [comment]
Merged. Closing.
