### ISSUE TITLE
Remove unused ODM2.apiCustomType.py and ODM2.models_sqlite.py

### ISSUE THREAD

**Issue by emiliom** [ODM2/ODM2PythonAPI#60]
It's been [mentioned](https://github.com/ODM2/ODM2PythonAPI/issues/#27#issuecomment-174112296) [before](https://github.com/ODM2/ODM2PythonAPI/issues/27#issuecomment-174607152), back in January and earlier, that `ODM2.apiCustomType.py` and `ODM2.models_sqlite.py` are no longer used.

@sreeder, can we remove them? Or just park them in a branch. FYI, I think @cdesyoun previously said that he created `models_sqlite.py` and it's no longer needed for anything.

**Comment by sreeder** [comment]
@emiliom these have been removed in the pull request #61

**Comment by emiliom** [comment]
Great!
