### ISSUE TITLE
error with psycopg2, connecting to postgresql database

### ISSUE THREAD

**Issue by miguelcleon** [ODM2/ODM2PythonAPI#63]
Hi, I tried to follow the instructions to install ODM2PythonAPI via the conda package but I received an error. psycopg2 for connecting to a postgresql database can be a pain to install not sure about including it in a conda package, I don't have experience with them. 

```python
import psycopg2
ImportError: No module named psycopg2
```

**Comment by emiliom** [comment]
psycopg2 installed on Ubuntu linux when I installed the odm2api conda package. But I know there were temporary problems a couple of weeks ago with the creation of the conda package for psycopg2 on Windows. I figured they had been solved.

Pinging @ocefpaf to ask about the status of `psycopg2` conda package on Windows.

**Comment by ocefpaf** [comment]
`psycopg2` with `Postgresql` is not OK on Windows yet. We could install the wheel, but ideally we should ship it with `Postgresql`.

See: https://github.com/conda-forge/staged-recipes/pull/291

I will add a workaround version at the ODM2 channel using the wheel and, once the conda-forge package is ready, we can change it.

**Comment by emiliom** [comment]
> psycopg2 with Postgresql is not OK on Windows yet

Ah, ok. Thanks for the temporary work around. Let us know (here, I guess) when it's available.

**Comment by ocefpaf** [comment]
>  Let us know (here, I guess) when it's available.

See https://github.com/ODM2/conda-recipes-ODM2/pull/32
