### ISSUE TITLE
Create PyPI package from new release (0.5.3-alpha)

### ISSUE THREAD

**Issue by emiliom** [ODM2/ODM2PythonAPI#79]
New odm2api [release (0.5.3-alpha) is out](https://github.com/ODM2/ODM2PythonAPI/releases/tag/v0.5.3-alpha), and the conda package has been updated.

There's interest in creating a PyPI package for this release. @ocefpaf, are you able to help with that? I know PyPI is not your strength.

FYI, @valentinedwv created an [odm2api PyPI package](https://pypi.python.org/pypi/odm2api/0.5.2) about 6 months ago. There were some issues with it (@ocefpaf, please see #71), but hopefully at a minimum this means that the groundwork is mostly laid out.

Related to this, I see @valentinedwv opened an issue (#35) here a year ago to setup a **PyPI account for ODM2**. There, he said: "Ideally, need a common email and some others to register so we can setup more than one admin." Dave, since you created at least two ODM2 PyPI packages in the past, I assume you created this account and can share the login info (offline) with us, so we can add other admins like @ocefpaf and possibly @horsburgh and me? BTW, let's close that old issue (#35) once Dave has shared that info and we've added other admins.

@ocefpaf will have very limited time (or none) next week, while traveling. So if this is too time consuming for this week (specially with other BiGCZ/ODM2 work already on his plate), it can wait till the week after next.

**Comment by ocefpaf** [comment]
> @ocefpaf, are you able to help with that?

Nope.

> I know PyPI is not your strength.

It is not about strength :smile: I need the credential for https://pypi.python.org/pypi/odm2api

After that is is a matter of issuing `python setup.py sdist --formats=gztar upload` from the proper updated branch. I can even automate that using Travis-CI and tagged releases.

**Comment by emiliom** [comment]
Ok, so we just need the credentials from @valentinedwv. 

But to be clear, I'd like you to double check that the requirements/setup configs are "fine" for issuing a PyPI package from the latest tagged release. They probably are, but a second look won't hurt.

**Comment by ocefpaf** [comment]
> But to be clear, I'd like you to double check that the requirements/setup configs are "fine" for issuing a PyPI package from the latest tagged release. They probably are, but a second look won't hurt.

They are OK. I will rebase and re-organize #74 to ensure that we don't need to worry about that in the next release.

**Comment by valentinedwv** [comment]
added ocefpaf to odm2api and wofpy

**Comment by emiliom** [comment]
> added ocefpaf to odm2api and wofpy.

Thanks, Dave!

> can emiliom and horsburg register at pypi

I'm now registered as "emiliom"
