### ISSUE TITLE
Travis-CI is broken due to a new image

### ISSUE THREAD

**Issue by ocefpaf** [ODM2/ODM2PythonAPI#88]
Travis-CI changed from a `Ubuntu precise` image, which reached the EOL, to the `Ubuntu Trusty`, the new LTS image. See https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

This change caused some breakages in the testing framework b/c it relied on packages from `apt` that are no longer available in the new image. The options are:

1. pin to the older image for as long as Travis-CI allows it;
2. find the equivalent packages in the new image;
3. figure out what is really needed and find conda packages from them.

I am looking into the problem and we can probably do `1` right now while we choose between `2` and `3` as a long term solution. (I prefer `3` BTW.)

**Comment by emiliom** [comment]
@ocefpaf, can we close this issue?

**Comment by ocefpaf** [comment]
> @ocefpaf, can we close this issue?

We are pinned to the old image and that one can go away without much warning, so I'd rather keep this opened to remind us to address the migration to the new one.

PS: I am running tests every since to try to figure out how to fire up the database in the new Image in my fork. See the `test` an `appveyor` branches. I hope to have a PR soon.

**Comment by emiliom** [comment]
Thanks. I was just going over some old issues, for no particular reason than to clean up.
