### ISSUE TITLE
getAffiliations `personfirst`, `personlast`, and `orgcode` not working. 

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2PythonAPI#95]
The query for Affiliations based on `personfirst`, `personlast`, and `orgcode` doesn't seem to be working. When I enter those parameters, I get everything, rather than the Affiliation with the specified filtering. 

I think the problem is that the [code](https://github.com/ODM2/ODM2PythonAPI/blob/master/odm2api/ODM2/services/readService.py#L557) is trying to filter, but since the values are not in the base query, it's not able to query correctly.

**Comment by emiliom** [comment]
Fixed by PR #96. Closing.
